### ISSUE TITLE
Track user on rollbar

### ISSUE THREAD

**Issue by JoydS** [rollbar/rollbar-php-symfony3-bundle#11]
Hello,
Is it possible to track which people have errors with this bundle ?

**Comment by JoydS** [comment]
Is it ready on master ?

**Comment by ArturMoczulski** [comment]
Hey @JoydS 

`master` is going through a major refactor. It's unstable, but should be working. See here how to track the user: https://github.com/rollbar/rollbar-php-symfony3-bundle#person-configuration-option

**Note:** the new refactor is not backwards compatible, so you will need to make changes to your `app/config/config.yml` or `app/config/config_*.yml`. See more info here: https://github.com/rollbar/rollbar-php-symfony3-bundle#installation

You can use `master` right away or if you want to wait for stable, I should be releasing a tag tomorrow.
