### ISSUE TITLE
Problem installing with composer: package not found on packagist

### ISSUE THREAD

**Issue by arendjantetteroo** [rollbar/rollbar-php-symfony3-bundle#14]
I tried 
composer require rollbar/rollbar-php-symfony3-bundle

 Problem 1
    - The requested package rollbar/rollbar-php-symfony3-bundle could not be found in any version, there may be a typo in the package name.

Is this bundle with this name on packagist already?

**Comment by arendjantetteroo** [comment]
As a temporary workaround i put this git repo in the vcs section of composer.json.

**Comment by ArturMoczulski** [comment]
@arendjantetteroo This has been now published on packagist: https://packagist.org/packages/rollbar/rollbar-php-symfony3-bundle
